<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\Build\ChurchManager.Common.props" />

    <!--Sets the build output directory to a custom folder when in development-->
    <!--the docker build will build these separately and copy to the correct place-->
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>..\..\API\ChurchManager.Api\Plugins\Payments.PayFast\</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>   

    <ItemGroup>
      <ProjectReference Include="..\..\Core\ChurchManager.Domain\ChurchManager.Domain.csproj" />
      <ProjectReference Include="..\..\Infrastructure\ChurchManager.Infrastructure\ChurchManager.Infrastructure.csproj" />
    </ItemGroup>

</Project>
