using ChurchManager.Domain.Features.Churches;
using ChurchManager.Domain.Features.Finances;
using ChurchManager.Features.Finances.Services;
using ChurchManager.Infrastructure.Abstractions.Configuration;
using ChurchManager.Infrastructure.Persistence.Contexts;
using ChurchManager.Infrastructure.Persistence.Repositories;
using ChurchManager.Infrastructure.Persistence.Tests.Helpers;
using ChurchManager.Infrastructure.Shared.BankImport;
using CodeBoss.MultiTenant;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Moq;
using Xunit;
using Xunit.Abstractions;

namespace ChurchManager.Infrastructure.Persistence.Tests;

public class BankStatementProcessor_Tests
{
    private readonly DbContextOptions<ChurchManagerDbContext> _options =
        new DbContextOptionsBuilder<ChurchManagerDbContext>()
            .UseNpgsql("Server=localhost;Port=5432;Database=churchmanager_db;User Id=admin;password=P455word1;")
            //.UseLoggerFactory(_loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
            .Options;
    private readonly Mock<IDistributedCache> _cacheMock;
    private readonly Mock<ITenantCurrentUser> _currentUserMock;
    private readonly AppConfig _appConfig;
    private readonly QueryCache _queryCache;
    
    private readonly ITestOutputHelper _output;

    public BankStatementProcessor_Tests(ITestOutputHelper output)
    {
        _output = output;
        
        // Setup mocks
        _cacheMock = new Mock<IDistributedCache>();
        _currentUserMock = new Mock<ITenantCurrentUser>();
        _appConfig = new AppConfig { DefaultCacheTimeMinutes = 30 };

        // Setup tenant information
        _currentUserMock.Setup(x => x.Tenant).Returns("test-tenant");

        // Create instance of the system under test
        _queryCache = new QueryCache(_cacheMock.Object, _currentUserMock.Object, _appConfig);
    }
    
    [Fact]
    public async Task should_process_bankstatement_references()
    {
        var ofxFilePath = "./Files/sample.ofx";
        using (var dbContext = new ChurchManagerDbContext(_options, new LocalTenantProvider(), null))
        {
            var churchesDb = new CacheGenericDbRepository<Church>(dbContext, _queryCache);
            var fundsDb = new CacheGenericDbRepository<Fund>(dbContext, _queryCache);
            var benefactorsDb = new CacheGenericDbRepository<Benefactor>(dbContext, _queryCache);
            var peopleDb = new PersonDbRepository(dbContext, _queryCache);
            
            var resolver = new GivingReferenceResolver(churchesDb, peopleDb, fundsDb, benefactorsDb, _queryCache);
            
            // Read and import bank statement
            using var stream = File.OpenRead(ofxFilePath);
            var importer = new OfxBankStatementImporter();
            var importOperation = await importer.ImportAsync(stream, "sample.ofx");
            
            // Process Bank statement
            var sut = new BankStatementProcessor(resolver);
            var result = await sut.ProcessAsync(importOperation.Result);
            
            Assert.True(result.IsSuccess);
        }

        

    }
}