using ChurchManager.Domain.Common;
using ChurchManager.Domain.Features.Churches;
using ChurchManager.Domain.Features.Groups;
using ChurchManager.Domain.Features.People;
using ChurchManager.Domain.Features.Permissions;
using ChurchManager.Domain.Features.Permissions.Repositories;
using ChurchManager.Domain.Features.Permissions.Services;
using ChurchManager.Features.Auth.Services;
using ChurchManager.Infrastructure.Persistence.Contexts;
using ChurchManager.Infrastructure.Persistence.Repositories;
using ChurchManager.Infrastructure.Persistence.Tests.Helpers;
using CodeBoss.AspNetCore.CbDateTime;
using Codeboss.Types;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Xunit;
using Xunit.Abstractions;

namespace ChurchManager.Infrastructure.Persistence.Tests;

public class Permission_Tests
{
    private readonly DbContextOptions<ChurchManagerDbContext> _options =
        new DbContextOptionsBuilder<ChurchManagerDbContext>()
            .UseNpgsql("Server=localhost;Port=5432;Database=churchmanager_db;User Id=admin;password=P455word1;")
            //.UseLoggerFactory(_loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
            .Options;
    
    private readonly ITestOutputHelper _output;
    private readonly IDateTimeProvider _dateTimeProvider;
    
    public Permission_Tests(ITestOutputHelper output)
    {
        _output = output;
        _dateTimeProvider = new CodeBossDateTimeProvider(Options.Create(new DateTimeOptions
        {
            TimeZone = "South Africa Standard Time"
        }), null);
    }

    [Fact]
    public async Task ChurchGroupAdmin_Should_See_All_Churches_In_Group()
    {
        using (var dbContext = new ChurchManagerDbContext(_options, new NoneTenantProvider(), null))
        {
            await dbContext.Database.EnsureCreatedAsync();
            
            var rolesDb = new UserLoginRoleDbRepository(dbContext, _dateTimeProvider);
            var permissionsDb = new EntityPermissionDbRepository(dbContext, _dateTimeProvider);
            var service = new PermissionService(rolesDb, permissionsDb, dbContext);
            
            // Arrange
            var (churchGroup, churches) = await SetupChurchGroupWithChurches(dbContext);
            var userLoginRole = await SetupUserWithDynamicPermission("ChurchGroup", churchGroup.Id, "Church", dbContext);

            // Act
            var query = dbContext.Church.AsQueryable();
            var filteredChurches = await service
                .FilterByPermissionAsync(userLoginRole.UserLoginId, query, "View");
            var result = await filteredChurches.ToListAsync();

            // Assert
            Assert.Equal(2, result.Count);
            Assert.All(result, church => 
                Assert.Equal(churchGroup.Id, church.ChurchGroupId));
        }
    }
    
    private async Task<(ChurchGroup, List<Church>)> SetupChurchGroupWithChurches(ChurchManagerDbContext _context)
    {
        var churchGroup = new ChurchGroup { Name = "Test Church Group" };
        var churches = new List<Church>
        {
            new() { Name = "Church 1", ChurchGroup = churchGroup },
            new() { Name = "Church 2", ChurchGroup = churchGroup }
        };
        _context.Church.AddRange(churches);
        await _context.SaveChangesAsync();

        return (churchGroup, churches);
    }
    
    private async Task<Church> SetupChurchWithGroups(ChurchManagerDbContext _context)
    {
        var church = new Church { Name = "Test Church" };

        var groups = new[]
        {
            new Group { Name = "Group 1", Church = church },
            new Group { Name = "Group 2", Church = church }
        };
        _context.Group.AddRange(groups);
        await _context.SaveChangesAsync();

        return church;
    }
    
    private async Task<UserLoginRole> SetupUserWithDynamicPermission(string scopeType, int scopeId, string entityType, ChurchManagerDbContext _context)
    {
        var family = new Family() { Address = new Address() };
        var person = new Person { Family = family};
        var permission = new EntityPermission
        {
            EntityType = entityType,
            IsDynamicScope = true,
            ScopeType = scopeType,
            ScopeId = scopeId,
            CanView = true,
            CanEdit = true
        };
        var role = new UserLoginRole("TestRole")
        {
            Permissions = [permission]
        };
        var userLogin = new UserLogin 
        { 
            Username = "test@test.com",
            Password = "hash",
            Roles = [role],
            Tenant = "Tenant1",
            Person = person
        };
        _context.UserLogin.Add(userLogin);
        await _context.SaveChangesAsync();
        
        return role;
    }
    
    private async Task<UserLoginRole> SetupUserWithExplicitPermission(string entityType, int[] entityIds, ChurchManagerDbContext _context)
    {
        var family = new Family() { Address = new Address() };
        var person = new Person { Family = family};
        var permission = new EntityPermission
        {
            EntityType = entityType,
            EntityIds = entityIds,
            IsDynamicScope = false,
            CanView = true,
            CanEdit = true
        };
        var role = new UserLoginRole("TestRole")
        {
            Permissions = [permission]
        };
        var userLogin = new UserLogin 
        { 
            Username = "test@test.com",
            Password = "hash",
            Roles = [role],
            Tenant = "Tenant1",
            Person = person
        };
        _context.UserLogin.Add(userLogin);
        await _context.SaveChangesAsync();

        return role;
    }
}

// Helper extensions for testing
public static class TestExtensions
{
    public static async Task<T> FirstOrThrowAsync<T>(this IQueryable<T> query)
    {
        var result = await query.FirstOrDefaultAsync();
        if (result == null) throw new InvalidOperationException("No entity found");
        
        return result;
    }
}