<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <Import Project="..\..\Build\ChurchManager.Common.props" />
  <ItemGroup>
    <PackageReference Include="Convey.CQRS.Queries" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChurchManager.Application.ViewModels\ChurchManager.Application.ViewModels.csproj" />
  </ItemGroup>
</Project>